---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a-team
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/zzztimbo/crossplane-tutorial.git
    targetRevision: HEAD
    path: a-team
  destination:
    server: https://kubernetes.default.svc
    namespace: a-team
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
